export { Hero } from "./Hero";
export { HowItWorks } from "./HowItWorks";
export { Features } from "./Features";
export { Pricing } from "./Pricing";
export { SocialProof } from "./SocialProof";
export { Analytics } from "./Analytics";
export { Navbar } from "./Navbar";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
